
-- Q3. System security by monitoring suspicious login behavior.


-- Create a table named login_audit to store all login attempts.

CREATE TABLE login_audit_one (
    audit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR2(50),
    attempt_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status       VARCHAR2(20), -- 'SUCCESS' or 'FAILED'
    ip_address   VARCHAR2(50)
);


-- Create another table named security_alerts to store alerts for suspicious activity.

CREATE TABLE security_alerts_one (
    alert_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(50),
    failed_count   NUMBER,
    alert_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    alert_message  VARCHAR2(255),
    contact_email  VARCHAR2(100)
);


-- Create a trigger that fires after each failed login attempt (assume the application inserts login attempts into login_audit)

CREATE OR REPLACE TRIGGER trg_detect_suspicious_login
AFTER INSERT ON login_audit_one
FOR EACH ROW
WHEN (NEW.status = 'FAILED') -- Only fire on failures
DECLARE
    v_fail_count NUMBER;
    PRAGMA AUTONOMOUS_TRANSACTION; -- Allows querying the table being inserted into
BEGIN
    -- Count failed attempts for this user for the current day
    -- We filter by TRUNC(attempt_time) to compare just the date part (ignoring time)
    SELECT COUNT(*)
    INTO v_fail_count
    FROM login_audit_one
    WHERE username = :NEW.username
      AND status = 'FAILED'
      AND TRUNC(attempt_time) = TRUNC(SYSDATE);

    -- LOGIC: The Autonomous query sees committed rows.
    -- If v_fail_count is 2, it means there were 2 PREVIOUS failures.
    -- The current insertion (which triggered this) is the 3rd one.
    
    IF v_fail_count >= 2 THEN
        INSERT INTO security_alerts_one (
            username, 
            failed_count, 
            alert_message, 
            contact_email
        ) VALUES (
            :NEW.username, 
            v_fail_count + 1, -- +1 to include the current attempt
            'Suspicious Activity: Multiple failed login attempts detected.',
            'security@yourcompany.com'
        );
        
        -- Commit the alert insertion (required for autonomous transactions)
        COMMIT;
    END IF;
    
    -- Ensure we commit purely the read operation if no insert happened
    COMMIT;
END;
/



-- ========================================================
-- TESSTING 
-- ========================================================

-- Attempt 1
INSERT INTO login_audit_one (username, status, ip_address) 
VALUES ('hacker_bob', 'FAILED', '192.168.1.50');

-- Attempt 2
INSERT INTO login_audit_one (username, status, ip_address) 
VALUES ('hacker_bob', 'FAILED', '192.168.1.50');

-- Attempt 3
INSERT INTO login_audit_one (username, status, ip_address) 
VALUES ('hacker_bob', 'FAILED', '192.168.1.50');



-- Check the results
SELECT * FROM login_audit_one WHERE username = 'hacker_bob';
SELECT * FROM security_alerts_one;


-- Expected Result:
--     login_audit: Should show 3 rows.
--     security_alerts: Should show 1 row.
--         failed_count: Should be 3.
--         alert_message: Should say "Suspicious Activity..."